Repository f-lab-edu/running-mate, pull requests merged in 2022-01, with the labels that each got.

#74 argument resolver 이용으로 세션 유저 정보와 요청 로그인 정보 비교 기능 추가
  src/main/java/com/runningmate/runningmate/common/Resolver/LoginUserIdArgumentResolver.java
  src/main/java/com/runningmate/runningmate/common/annotation/SessionLoginUser.java
  src/main/java/com/runningmate/runningmate/configuration/WebConfig.java
  src/main/java/com/runningmate/runningmate/user/controller/UserController.java
  src/main/java/com/runningmate/runningmate/user/service/UserService.java
Labels: refactoring

#61 유저 스킬 수정
  src/main/java/com/runningmate/runningmate/user/controller/UserController.java
  src/main/java/com/runningmate/runningmate/user/dto/Request/UserSkillAddReqeustDto.java
  src/main/java/com/runningmate/runningmate/user/mapper/UserSkillMapper.java
  src/main/java/com/runningmate/runningmate/user/repository/UserSkillRepository.java
  src/main/java/com/runningmate/runningmate/user/repository/impl/MybatisUserSkillRepository.java
  src/main/java/com/runningmate/runningmate/user/service/UserService.java
  src/main/resources/mapper/user/userSkill.xml
  src/test/java/com/runningmate/runningmate/user/UserServiceTest.java
Labels: develop

#78 Master(insert,update,delete) / Slave(select) 분리를 위한 Config 추가 및 설정파일 추가
  src/main/java/com/runningmate/runningmate/configuration/DataBaseConfiguration.java
  src/main/java/com/runningmate/runningmate/dataSource/DataSourceType.java
  src/main/java/com/runningmate/runningmate/dataSource/ReplicationRoutingDataSource.java
  src/main/java/com/runningmate/runningmate/user/controller/UserController.java
  src/main/java/com/runningmate/runningmate/user/mapper/UserMapper.java
  src/main/resources/application.properties
Labels: develop

#75 프로젝트 좋아요 기능 개발
  .DS_Store
  .gitignore
  src/.DS_Store
  src/main/.DS_Store
  src/main/java/.DS_Store
  src/main/java/com/.DS_Store
  src/main/java/com/runningmate/.DS_Store
  src/main/java/com/runningmate/runningmate/.DS_Store
  src/main/java/com/runningmate/runningmate/common/RedisCacheService.java
  src/main/java/com/runningmate/runningmate/common/configuration/CacheConfiguration.java
  src/main/java/com/runningmate/runningmate/common/configuration/DataBaseConfiguration.java
  src/main/java/com/runningmate/runningmate/common/configuration/JasyptConfig.java
  src/main/java/com/runningmate/runningmate/common/configuration/ModelMapperConfiguration.java
  src/main/java/com/runningmate/runningmate/common/configuration/RedisConfiguration.java
  src/main/java/com/runningmate/runningmate/like/controller/LikeController.java
  src/main/java/com/runningmate/runningmate/like/domain/repository/LikeCacheRepository.java
  src/main/java/com/runningmate/runningmate/like/service/LikeService.java
  src/main/java/com/runningmate/runningmate/project/domain/mapper/ProjectMapper.java
  src/main/java/com/runningmate/runningmate/project/domain/repository/MybatisProjectRepository.java
  src/main/java/com/runningmate/runningmate/project/domain/repository/ProjectRepository.java
  src/main/resources/mapper/project/ProjectMapper.xml
Labels: develop, review

#85 @Transactional(readOnly = true) 어노테이션 mapper -> service 수정
  src/main/java/com/runningmate/runningmate/user/mapper/UserMapper.java
  src/main/java/com/runningmate/runningmate/user/service/SessionLoginService.java
  src/main/java/com/runningmate/runningmate/user/service/UserService.java
Labels: refactoring
